[WIP][JENKINS-30680] Pipeline compatibility
jenkinsci/custom-tools-plugin pull request #27
Opened 2017-07-24 13:38 UTC by alexbrjo

Pipeline compatibility. see [JENKINS-30680](https://issues.jenkins-ci.org/browse/JENKINS-30680)

- [X] Compatibility with pipeline
- [X] Snippet generator
- [X]  Used tools action added to job
  - [ ] aesthetic jelly for the action page
- [ ] backwards / binary compatibility 

**Implementation**
Since `BuildWrapper#decorateLauncher()` is only honored for `AbstractProject`'s, I tried to keep parity between FreeStyle and Workflow jobs by moving the logic for adding environment variables to `BuildWrapper#setup()`

2017-07-24 15:06 UTC, oleg-nenashev requested changes

2017-07-24 15:06 UTC, oleg-nenashev commented on src/main/java/com/synopsys/arc/jenkinsci/plugins/customtools/multiconfig/MulticonfigWrapperOptions.java
> +public class MulticonfigWrapperOptions implements Serializable, Describable<MulticonfigWrapperOptions>, ExtensionPoint {
You do not need `ExtensionPoint` here from what I see 🐜

2017-08-01 19:12 UTC, alexbrjo commented on src/main/java/com/cloudbees/jenkins/plugins/customtools/CustomToolInstallWrapper.java
> -    public Environment setUp(AbstractBuild build, Launcher launcher,
There is some large refactoring that needs to be done here, but to take care of some of the pipeline unrelated diff consider #28

2017-09-18 12:54 UTC, oleg-nenashev commented
@alexbrjo Hi Alex. FYI I have reopened this pull-request. I am working on removing Extended Choice dependency as a part of [JENKINS-32662](https://issues.jenkins-ci.org/browse/JENKINS-32662) / [JENKINS-46141](https://issues.jenkins-ci.org/browse/JENKINS-46141)/other such issues.

It apepars it is not possible to do the refactoring in a compatible way due to the architecture issues I have introduced in 2013. But it's too hot due to the security issue in Extended Choice, so I lean towards breaking the compatibility and releasing 1.0.

It makes the current pull request compliant, so I will probably refactor and land this pull request in 1.0

2017-09-18 14:06 UTC, oleg-nenashev commented
FTR the parallel work is here: https://github.com/jenkinsci/customtools-plugin/pull/29

2026-03-27 12:19 UTC, closed without merging